"""Initial migration.

Revision ID: 4a4933950036
Revises: 
Create Date: 2024-12-28 16:59:05.037284

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "4a4933950036"
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "execution",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("timestamp", sa.DateTime(), nullable=True),
        sa.Column("commands", sa.Integer(), nullable=False),
        sa.Column("result", sa.Integer(), nullable=False),
        sa.Column("duration", sa.Float(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("execution")
    # ### end Alembic commands ###
