version: '3.8'

services:
  app:
    container_name: robot-cleaning-service-app
    build: .
    ports:
      - "5000:5000"
    volumes:
      - ./app:/app
    environment:
      - FLASK_APP=main.py
      - DATABASE_URI=postgresql://user:password@db:5432/robot_service
    depends_on:
      db:
        condition: service_healthy  # Wait until db service is healthy
    command: >
      sh -c "flask db upgrade && flask run --host=0.0.0.0 --port=5000"
    healthcheck:  # Add a health check for the app
      test: ["CMD", "curl", "-f", "http://localhost:5000/health"]
      interval: 10s
      timeout: 5s
      retries: 5

  db:
    image: postgres:13
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: robot_service
    ports:
      - "5433:5432"
    healthcheck:  # Add a health check for the database
      test: ["CMD-SHELL", "pg_isready -U user -d robot_service"]
      interval: 5s
      retries: 5
    volumes:
      - db_data:/var/lib/postgresql/data

volumes:
  db_data:
