name: CI Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'

    - name: Install Docker Compose
      run: |
        sudo apt-get update
        sudo apt-get install -y docker-compose

    - name: Build and Run Docker Containers
      run: |
        make up-ci

    - name: Wait for Server to Be Ready
      run: |
        for i in {1..10}; do
          if curl -f http://localhost:5000/health; then
            echo "Server is ready!"
            break
          fi
          echo "Waiting for server to be ready..."
          sleep 5
        done

    - name: List Docker Containers
      run: |
        docker ps

    - name: Test Code Coverage
      run: |
        make test-coverage

    - name: Tear Down Services
      if: always()
      run: |
        docker compose down
